### ISSUE TITLE
Unclear problem to solve "Exception: Modular references are not supported in this version"

### ISSUE THREAD

**Issue by ChameleonRed** [koxudaxi/fastapi-code-generator#226]
It is not clear for me how to solve this problem - where is problem and why is problem?

Traceback (most recent call last):
  File "C:\root\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\root\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\root\Python\Python39\Scripts\fastapi-codegen.exe\__main__.py", line 7, in <module>
  File "C:\root\Python\Python39\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\root\Python\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\root\Python\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\root\Python\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\root\Python\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\root\Python\Python39\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\root\Python\Python39\lib\site-packages\fastapi_code_generator\__main__.py", line 47, in main
    return generate_code(input_name, input_text, output_dir, template_dir, model_path)
  File "C:\root\Python\Python39\lib\site-packages\fastapi_code_generator\__main__.py", line 86, in generate_code
    raise Exception('Modular references are not supported in this version')
Exception: Modular references are not supported in this version

**Comment by yyamano** [comment]
@ChameleonRed @AnthonyA1223 I'm wondering if you can provide an api spec file to reproduce the issue.

**Comment by AnthonyA1223** [comment]
> @ChameleonRed @AnthonyA1223 I'm wondering if you can provide an api spec file to reproduce the issue.

It's been a while but if I remember correctly I used it on the following:

https://github.com/emerout/ocpi-swagger-sample/blob/master/spec/swagger.yaml

**Comment by yyamano** [comment]
Thank you @AnthonyA1223 

I tried to reproduce the problem with it, but I got different errors:

```
ValidationError: 2 validation errors for JsonSchemaObject
properties -> parking_restrictions -> required
  value is not a valid list (type=type_error.list)
properties -> parking_restrictions
  value could not be parsed to a boolean (type=type_error.bool)
```
