### ISSUE TITLE
Need to bump datamodel-code-generator to 0.11.18

### ISSUE THREAD

**Issue by bd-cp** [koxudaxi/fastapi-code-generator#230]
Following error is thrown with the current version using `datamodel-code-generator==0.11.15`:
```
Traceback (most recent call last):
  File "/a/path/bin/fastapi-codegen", line 8, in <module>
    sys.exit(app())
  File "/a/path/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/a/path/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/a/path/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/a/path/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/a/path/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/a/path/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/a/path/lib/python3.8/site-packages/fastapi_code_generator/__main__.py", line 47, in main
    return generate_code(input_name, input_text, output_dir, template_dir, model_path)
  File "/a/path/lib/python3.8/site-packages/fastapi_code_generator/__main__.py", line 79, in generate_code
    models = parser.parse()
  File "/a/path/lib/python3.8/site-packages/datamodel_code_generator/parser/base.py", line 433, in parse
    code_formatter: Optional[CodeFormatter] = CodeFormatter(
  File "/a/path/lib/python3.8/site-packages/datamodel_code_generator/format.py", line 44, in __init__
    path = root / "pyproject.toml"
TypeError: unsupported operand type(s) for /: 'tuple' and 'str'
```

Simple workaround until it is bumped:
`pip install -U datamodel-code-generator==0.11.18`

**Comment by jayvdb** [comment]
I think this issue should be closed.
