### ISSUE TITLE
Impossible to install package with python3.10

### ISSUE THREAD

**Issue by CamilleBarnier** [koxudaxi/fastapi-code-generator#405]
When installing have this error:

`Collecting ruamel.yaml.clib>=0.2.7
  Using cached ruamel.yaml.clib-0.2.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (526 kB)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/cbarnier/.local/lib/python3.10/site-packages (from anyio<5.0,>=3.0->httpcore<0.17.0,>=0.15.0->httpx->datamodel-code-generator[http]==0.16.1->fastapi-code-generator) (1.2.0)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError`

**Comment by IvanZadorozhniy** [comment]
it helped me with the same problem
`pip install --upgrade pip setuptools`

**Comment by koxudaxi** [comment]
Resolved by #599.
