### ISSUE TITLE
ValueError: 'template/main.jinja2' is not in the subpath

### ISSUE THREAD

**Issue by nadworny** [koxudaxi/fastapi-code-generator#84]
I'm trying to make my project compatible with poetry so I have to add a start method where I invoke uvicorn so that I can have the following in the poetry run script:
```
[tool.poetry.scripts]
run = "skeleton_python_api.main:start"
```

I have the following structure of a project:
```
├── README.md
├── openapi.yaml
├── poetry.lock
├── pyproject.toml
├── skeleton_python_api
│   ├── __init__.py
│   ├── main.py
│   └── models.py
├── template
│   └── main.jinja2
└── tests
    ├── __init__.py
    └── test_skeleton_python_api.py
```

While running the following command:
```
(skeleton-python-api-PB31_aPS-py3.9) ➜  skeleton-python-api git:(master) ✗ fastapi-codegen --input openapi.yaml --output skeleton_python_api -t template 
```

I'm getting an error:
```
Traceback (most recent call last):
  File "/Users/bartosz.nadworny/Library/Caches/pypoetry/virtualenvs/skeleton-python-api-PB31_aPS-py3.9/bin/fastapi-codegen", line 8, in <module>
    sys.exit(app())
  File "/Users/bartosz.nadworny/Library/Caches/pypoetry/virtualenvs/skeleton-python-api-PB31_aPS-py3.9/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/bartosz.nadworny/Library/Caches/pypoetry/virtualenvs/skeleton-python-api-PB31_aPS-py3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bartosz.nadworny/Library/Caches/pypoetry/virtualenvs/skeleton-python-api-PB31_aPS-py3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/bartosz.nadworny/Library/Caches/pypoetry/virtualenvs/skeleton-python-api-PB31_aPS-py3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bartosz.nadworny/Library/Caches/pypoetry/virtualenvs/skeleton-python-api-PB31_aPS-py3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/bartosz.nadworny/Library/Caches/pypoetry/virtualenvs/skeleton-python-api-PB31_aPS-py3.9/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/bartosz.nadworny/Library/Caches/pypoetry/virtualenvs/skeleton-python-api-PB31_aPS-py3.9/lib/python3.9/site-packages/fastapi_code_generator/__main__.py", line 28, in main
    return generate_code(input_name, input_text, output_dir, template_dir)
  File "/Users/bartosz.nadworny/Library/Caches/pypoetry/virtualenvs/skeleton-python-api-PB31_aPS-py3.9/lib/python3.9/site-packages/fastapi_code_generator/__main__.py", line 50, in generate_code
    relative_path = target.relative_to(template_dir.absolute())
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 928, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'template/main.jinja2' is not in the subpath of '/Users/bartosz.nadworny/workspace/space/skeleton-python-api/template' OR one path is relative and the other is absolute.
```

Template:
```
from __future__ import annotations

import uvicorn
from fastapi import FastAPI

{{imports}}

app = FastAPI(
    {% if info %}
    {% for key,value in info.items() %}
    {{ key }} = "{{ value }}",
    {% endfor %}
    {% endif %}
    )


{% for operation in operations %}
@app.{{operation.type}}('{{operation.snake_case_path}}', response_model={{operation.response}})
def {{operation.function_name}}({{operation.snake_case_arguments}}) -> {{operation.response}}:
    {%- if operation.summary %}
    """
    {{ operation.summary }}
    """
    {%- endif %}
    pass
{% endfor %}


def start():
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

# Env
macos
python 3.9.0
fastapi-code-generator 0.1.0

**Comment by koxudaxi** [comment]
@nadworny 
Thank you for creating this issue.
I fixed the problem. And  I released a new version as `0.1.1`.
